### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by millxisyes**
Made the instructions easier to understand, for people who are slow in the head.

### CODE REVIEW

**Review by millxisyes — COMMENTED** [review]
This has gyat to be sigma.

**Comment by BackslashG** [comment]
Sorry, make it better.

**Comment by millxisyes** [comment]
Okay.

**Comment by BackslashG** [comment]
I could not understand it

**Comment by BackslashG** [comment]
WOAH WTF

**Comment by BackslashG** [comment]
COMMENTS UPDATE IN RELA TIME

**Comment by BackslashG** [comment]
THATS HOT

**Comment by millxisyes** [comment]
WGF

**Comment by millxisyes** [comment]
WTFFFF

**Comment by BackslashG** [comment]
HI MILLX

**Comment by millxisyes** [comment]
HOT ASF

**Comment by millxisyes** [comment]
HI

**Comment by BackslashG** [comment]
THIS IS THE NEW DISCORD

**Comment by millxisyes** [comment]
SAY "PENIS" THE SECOND U SEE THIS

**Comment by BackslashG** [comment]
PENMS

**Comment by BackslashG** [comment]
I HATE HOW U CANT PRESS ENTER

**Comment by millxisyes** [comment]
WITHJFN

**Comment by millxisyes** [comment]
Slashy are u here

**Comment by BackslashG** [comment]
AND SEND IT

**Comment by millxisyes** [comment]
Say "PENIS" The seocnd us eet hat

**Comment by millxisyes** [comment]
say penis rn

**Comment by millxisyes** [comment]
needa test

**Comment by millxisyes** [comment]
the

**Comment by millxisyes** [comment]
latency

**Comment by millxisyes** [comment]
```c#
sussy baka
```

**Comment by BackslashG** [comment]
LMAO i was AFK

**Comment by BackslashG** [comment]
cuz im sussy like that

**Comment by millxisyes** [comment]
LMAOp

**Comment by BackslashG** [comment]
lol griddy

**Comment by millxisyes** [comment]
Say "penis"

**Comment by millxisyes** [comment]
die

**Pull request merged**
